version: "3"
services:
  app:
    container_name: chip-atlas
    image: ruby:3.2.2-slim
    volumes:
      - ${PWD}:/app
    ports:
      - 9292:9292
    command: bash -c "apt-get update -y && apt-get install -y lftp libffi-dev build-essential libpq-dev libsqlite3-dev && echo \"Setup finished\" && tail -f /dev/null"

