services:
  app:
    container_name: chip-atlas
    image: ruby:3.3-slim
    volumes:
      - ${PWD}:/app
    working_dir: /app
    ports:
      - 9292:9292
    command: bash -c "apt-get update -y && apt-get install -y build-essential libsqlite3-dev && bundle install && echo 'Setup finished' && tail -f /dev/null"

