source 'https://rubygems.org'

gem 'rake'
gem 'sinatra'
gem 'webrick'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rack-protection'
gem 'sqlite3'
gem 'haml'
gem 'sass-embedded'
gem 'redcarpet'
gem 'nokogiri'
gem 'unicorn'
gem 'rubyzip'
gem 'net-ping'
gem 'rackup'
